### ISSUE TITLE
Missing function for .send example

### ISSUE THREAD

**Issue by microbuilder** [adafruit/adafruit-io-node#1]
Hi Todd ... sorry to file this as an issue (couldn't find your adafruit address in my inbox), but there's a small typo here ... the function is missing in the example code: https://github.com/adafruit/io-client-node#send

Looks good, though!  I read through it just to see what the interface was like.

**Comment by toddtreece** [comment]
@microbuilder thanks! GitHub issues are the best way for me to keep track of this type of thing.

fixed by 0589a69461219df8cea3b6f6949789a39df8a4de
